### ISSUE TITLE
Issue with exchange_calendars and currencies (CCY)

### ISSUE THREAD

**Issue by KentFredo** [ValueRaider/yfinance-cache#58]
Hey everyone,
first of all thanks for the great library.

I have just switched from yfinance to this lib and am trying to get currency data such as 'EUR=X'.
YFC gets the exchange as CCY, which is not known by exchange_calendars. However, creating a custom calendar / creating an alias and linking to another calendar is not helping.

I am always receiving this exception from yfc.time.

    _raise Exception("Need to add mapping of exchange {} to xcal (ticker={})".format(exchange, self.ticker))
Exception: Need to add mapping of exchange CCY to xcal (ticker=EUR=X)_

I am quite new here.. how are you dealing with currency conversion and gettig currencies?

**Comment by ValueRaider** [comment]
I need FX rarely so just use yfinance direct. But I have FX and crypto working locally so expect an update soon.

**Comment by ValueRaider** [comment]
Checkout branch `feature/prices-updates`

**Comment by KentFredo** [comment]
That was quick, thanks a lot!
Just tested it briefly, branch looks fine so far.

**Comment by ValueRaider** [comment]
Are you ok to keep using branch? I'm working on some other price fixes, will release together.

**Comment by KentFredo** [comment]
Definitly, that is fine for me. 
So far, all changes working stable.
