### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by 731315163** [ValueRaider/yfinance-cache#64]
Exception has occurred: ValueError
numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
  File "C:\Users\zt\project\testyfc\test.py", line 2, in <module>
    import yfinance_cache as yfc
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by ValueRaider** [comment]
How did you install numpy and yfc?

**Comment by sonique6784** [comment]
you need to install numpy 1.26.4:
```
pip install numpy==1.26.4 
```
