### ISSUE TITLE
Options chain is not cached

### ISSUE THREAD

**Issue by ricardobranco777** [ValueRaider/yfinance-cache#75]
`AttributeError: 'Ticker' object has no attribute 'option_chain'`

**Comment by ValueRaider** [comment]
I don't use options so need feedback.
- What default aging period? 1 day? https://github.com/ValueRaider/yfinance-cache#aging
- what should happen to an option contract already in cache when it's refetched? Just overwrite?

**Comment by ricardobranco777** [comment]
> I don't use options so need feedback.
> 
> * What default aging period? 1 day? https://github.com/ValueRaider/yfinance-cache#aging

1 day is best.

> * What should happen to an option contract already in cache when it's refetched? Just overwrite?

Overwrite because there are things that change like price, volume and open interest.
